@startuml SecuenciaUnaMotoCruzaLaGrillaSinObstaculos

title Una moto atraviesa la grilla sin obstaculos\n y la cantidad de movimientos es X

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "vehiculo:vehiculo" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant "Direccion" as direccion
participant "Modificador" as modificador

activate tablero

loop Por cada Direccion X veces

    user -> tablero: mover(dir: Direccion)

    activate vehiculo

    tablero -> vehiculo: mover(dir: Direccion)

    activate celda

    vehiculo -> celda: mover(self, dir: Direccion)
    celda -> celda: obtenerEsquinas()

    loop Por cada calle
        activate calle

        celda -> calle: proximaEsquina(self)
        calle --> celda: esquinaSiguiente: Celda

        deactivate calle
    end

    activate direccion

    celda -> direccion: mover(f, c, [esquinas])
    direccion --> celda: celdaEnSiguienteDireccion

    deactivate direccion

    celda -> celda: obtenerCalleConEsquinas(self, celdaEnSiguienteDireccion)

    loop Por cada calle
        activate calle

        celda -> calle: contiene(self)
        calle --> celda: true
        celda -> calle: contiene(celdaEnSiguienteDireccion)
        calle --> celda: true

        deactivate calle
    end

    activate calle

    celda -> calle: cruzarCon(jug: vehiculo)

    activate modificador

    calle -> modificador: cruzarCon(jug: vehiculo)
    modificador -> vehiculo: sumarMovimientos(1)

    deactivate modificador
    deactivate calle

    celda --> vehiculo: celdaEnSiguienteDireccion
    vehiculo --> tablero: celda = celdaEnSiguienteDireccion\nmoviemientos + 1

    deactivate celda
    deactivate vehiculo

end


user -> tablero: movimientos()

activate vehiculo
tablero -> vehiculo: movimientos()
vehiculo --> tablero: X
deactivate vehiculo

tablero --> user: X

deactivate tablero

@enduml