@startuml SecuenciaUnaMotoCruzaLaGrillaSinObstaculos

title Una moto atraviesa la grilla sin obstaculos\n y la cantidad de movimientos es X

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "jugador:Jugador" as jugador
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant "Direccion" as direccion
participant "Modificador" as modificador

activate tablero

loop Por cada Direccion X veces

    user -> tablero: mover(dir: Direccion)

    activate jugador

    tablero -> jugador: mover(dir: Direccion)

    activate celda

    jugador -> celda: mover(self, dir: Direccion)
    celda -> celda: obtenerEsquinas()

    loop Por cada calle
        activate calle

        celda -> calle: proximaEsquina(self)
        calle --> celda: esquinaSiguiente: Celda

        deactivate calle
    end

    activate direccion

    celda -> direccion: mover(f, c, [esquinas])
    direccion --> celda: celdaEnSiguienteDireccion

    deactivate direccion

    celda -> celda: obtenerCalleConEsquinas(self, celdaEnSiguienteDireccion)

    loop Por cada calle
        activate calle

        celda -> calle: contiene(self)
        calle --> celda: true
        celda -> calle: contiene(celdaEnSiguienteDireccion)
        calle --> celda: true

        deactivate calle
    end

    activate calle

    celda -> calle: cruzarCon(jug: Jugador)

    activate modificador

    calle -> modificador: cruzarCon(jug: Jugador)
    modificador -> jugador: sumarMovimientos(1)

    deactivate modificador
    deactivate calle

    celda --> jugador: celdaEnSiguienteDireccion
    jugador --> tablero: celda = celdaEnSiguienteDireccion\nmoviemientos + 1

    deactivate celda
    deactivate jugador

end


user -> tablero: movimientos()

activate jugador
tablero -> jugador: movimientos()
jugador --> tablero: X
deactivate jugador

tablero --> user: X

deactivate tablero

@enduml