 @startuml SecuenciaVehiculoCambiaVehiculo
' Caso de uso 
' Un auto atraviesa la ciudad y se encuentra con un CambioDeVehiculo. Se cambia el auto.por una camioneta.

title Un vehiculo atraviesa la ciudad y se encuentra con un CambioDeVehiculo. 

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "jugador:Jugador" as jugador
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant ":CambioDeVehiculo" as cambioDeVehiculo
participant ":Vehiculo" as vehiculo

activate tablero

user -> tablero: mover(dir: Direccion)

activate jugador

tablero -> jugador: mover(dir: Direccion)

activate celda

jugador -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: Jugador)

deactivate celda

activate cambioDeVehiculo

calle -> cambioDeVehiculo: cruzarCon(jug: Jugador)

deactivate calle

cambioDeVehiculo -> jugador: reemplazarVehiculo()

activate vehiculo

jugador -> vehiculo : reemplazarVehiculo()

vehiculo --> jugador : vehiculo: Vehiculo 
deactivate vehiculo

cambioDeVehiculo -> jugador: sumarMovimiento(Y)
deactivate cambioDeVehiculo


deactivate celda

user -> tablero: movimientos()

tablero -> jugador: movimientos()
jugador --> tablero: X + Y
deactivate jugador

tablero --> user: X + Y

deactivate tablero

@enduml

