@startuml SecuenciaAutoCruzaUnPozoYEsPenalizado
' Caso de uso 
' Un auto atraviesa la ciudad y se encuentra con un Pozo. Es penalizado en tres movimientos.

title Un auto atraviesa la ciudad y se encuentra con un Pozo. Es penalizado en tres movimientos.

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "vehiculo:vehiculo" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant "pozo:Pozo" as pozo
participant "auto:Auto" as auto

' participant "Direccion" as direccion
' participant "Modificador" as modificador

activate tablero


user -> tablero: mover(dir: Direccion)

activate vehiculo

tablero -> vehiculo: mover(dir: Direccion)

activate celda

vehiculo -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: vehiculo)

deactivate celda
activate pozo

calle -> pozo: cruzarCon(jug: vehiculo)

deactivate calle

pozo -> vehiculo: obtenerVehiculo()

vehiculo --> pozo: auto: Auto

activate auto

pozo -> auto: pozo(vehiculo: vehiculo)

deactivate pozo

auto -> vehiculo: sumarMovimentos(3)

deactivate auto
deactivate calle
deactivate celda

user -> tablero: movimientos()
tablero -> vehiculo: movimientos()
vehiculo --> tablero: X + 3

deactivate vehiculo

tablero --> user: X + 3

deactivate tablero

@enduml

