 @startuml SecuenciaAutoCambiaVehiculo
' Caso de uso 
' Un auto atraviesa la ciudad y se encuentra con un CambioDeVehiculo. Se cambia el auto.por una camioneta.

title Un auto atraviesa la ciudad y se encuentra con un CambioDeVehiculo. Se cambia el auto por una camioneta

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "vehiculo:vehiculo" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant ":CambioDeVehiculo" as cambioDeVehiculo
participant "auto:Vehiculo" as vehiculo

activate tablero

user -> tablero: mover(dir: Direccion)

activate vehiculo

tablero -> vehiculo: mover(dir: Direccion)

activate celda

vehiculo -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: vehiculo)

deactivate celda

activate cambioDeVehiculo

calle -> cambioDeVehiculo: cruzarCon(jug: vehiculo)

deactivate calle

cambioDeVehiculo -> vehiculo: reemplazarVehiculo()

deactivate cambioDeVehiculo
activate vehiculo

vehiculo -> vehiculo : reemplazarVehiculo()

vehiculo --> vehiculo : camioneta: Camioneta4X4 

vehiculo -> vehiculo: sumarMovimiento(1)

deactivate vehiculo

deactivate celda

user -> tablero: movimientos()

tablero -> vehiculo: movimientos()
vehiculo --> tablero: X 
deactivate vehiculo

tablero --> user: X

deactivate tablero

@enduml

