@startuml SecuenciaMotoCambiaVehiculo
' Caso de uso 
' Una moto atraviesa la ciudad y se encuentra con un CambioDeVehiculo. Se cambia la moto por un auto.

title Una moto atraviesa la ciudad y se encuentra con un CambioDeVehiculo. Se cambia la moto por un auto.

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "vehiculo:vehiculo" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant ":CambioDeVehiculo" as cambioDeVehiculo
participant "moto:Vehiculo" as vehiculo


activate tablero

user -> tablero: mover(dir: Direccion)

activate vehiculo

tablero -> vehiculo: mover(dir: Direccion)

activate celda

vehiculo -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: vehiculo)

deactivate celda

activate cambioDeVehiculo

calle -> cambioDeVehiculo: cruzarCon(jug: vehiculo)

deactivate calle

cambioDeVehiculo -> vehiculo: reemplazarVehiculo()

deactivate cambioDeVehiculo
activate vehiculo

vehiculo -> vehiculo : reemplazarVehiculo()

vehiculo --> vehiculo : auto: Auto 

vehiculo -> vehiculo: sumarMovimiento(1)

deactivate vehiculo

deactivate celda

user -> tablero: movimientos()
tablero -> vehiculo: movimientos()
vehiculo --> tablero: X + 1
deactivate vehiculo

tablero --> user: X + 1

deactivate tablero

@enduml
