

@startuml sec-moto-atraviesa-grilla-sin-obs
' Caso de uso 
' Una moto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos.

title Una moto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos.

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "jugador:Jugador" as jugador
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant "pozo:Pozo" as pozo
participant "moto:Moto" as moto

activate tablero

user -> tablero: mover(dir: Direccion)

activate jugador

tablero -> jugador: mover(dir: Direccion)

activate celda

jugador -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: Jugador)

deactivate celda
activate pozo

calle -> pozo: cruzarCon(jug: Jugador)
deactivate calle
pozo -> jugador: obtenerVehiculo()

jugador --> pozo: moto: Moto

activate moto

pozo -> moto: pozo(jugador: Jugador)

deactivate pozo

moto -> jugador: sumarMovimentos(3)

deactivate moto
deactivate calle
deactivate celda

user -> tablero: movimientos()
tablero -> jugador: movimientos()
jugador --> tablero: X + 3

deactivate jugador

tablero --> user: X + 3

deactivate tablero

@enduml

