@startuml SecuenciaUnaMotoCruzaUnPozoYEsPenalizado
' Caso de uso 
' Una moto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos.

title Una moto atraviesa la ciudad y se encuentra con un Pozo. Es penalizada en tres movimientos.

Actor Usuario as user
participant "tablero:Tablero" as tablero
participant "vehiculo:vehiculo" as vehiculo
participant "celda:Celda" as celda
participant "calle:Calle" as calle
participant "pozo:Pozo" as pozo
participant "moto:Moto" as moto

activate tablero

user -> tablero: mover(dir: Direccion)

activate vehiculo

tablero -> vehiculo: mover(dir: Direccion)

activate celda

vehiculo -> celda: mover(self, dir: Direccion)

activate calle

celda -> calle: cruzarCon(jug: vehiculo)

deactivate celda
activate pozo

calle -> pozo: cruzarCon(jug: vehiculo)
deactivate calle
pozo -> vehiculo: obtenerVehiculo()

vehiculo --> pozo: moto: Moto

activate moto

pozo -> moto: pozo(vehiculo: vehiculo)

deactivate pozo

moto -> vehiculo: sumarMovimentos(3)

deactivate moto
deactivate calle
deactivate celda

user -> tablero: movimientos()
tablero -> vehiculo: movimientos()
vehiculo --> tablero: X + 3

deactivate vehiculo

tablero --> user: X + 3

deactivate tablero

@enduml

